Development
Angelesh1995/Apple-Clone pull request #1
Opened 2020-02-07 19:57 UTC by Angelesh1995

This project was about to clone an old Apple website using backgrounds and gradients.

2020-02-08 00:49 UTC, kobiyoyo commented
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-02-08 01:13 UTC, kobiyoyo commented
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-02-08 01:13 UTC, kobiyoyo requested changes
## Hi @Angelesh1995     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [ ] The project should have a descriptive README.md
### Make changes and submit another code review request.
*Happy coding*

2020-02-08 15:28 UTC, euqueme requested changes
> ### Pull Request Under The Review By Maria Eugenia Queme P. (TSE)

### Hello @Angelesh1995  :balloon: 

### Thank you for adding the Readme file as requested by the previous TSE :medal_sports: the gradient in your navbar is brilliant and  your use of backgrounds is stellar :star2:  still there are a couple of things to fix :hammer: 

## Body

- [ ] Add a [reset](https://meyerweb.com/eric/tools/css/reset/) at the beginning of your CSS file so your page doesn't set default browser properties as right now is adding 8px for the body

## Heroe Background

- [ ] It should take 100% of the page I put a suggestion in your code on how you could fix it and also avoids the scroll bar appearing in my screen :arrow_down: (something shifted after doing this? please fix it too) 

![image](https://user-images.githubusercontent.com/52209067/74087611-9de51b00-4a53-11ea-8d3a-6e38773709c3.png)

## Navbar

- [ ] The first button in your navbar is noticeably bigger than the other buttons, let's fix it

![image](https://user-images.githubusercontent.com/52209067/74087311-7ccefb00-4a50-11ea-8a9c-fc3a7b11778d.png)

## Footer

the footer's right column (Site Map | Hot News | RSS Feeds | ...) should have more space in between the left column with the two rows like the original

- Yours

![image](https://user-images.githubusercontent.com/52209067/74087673-38ddf500-4a54-11ea-98a2-ad8155c3b8f1.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74087682-4a270180-4a54-11ea-92e4-2f08861687dc.png)

## Readme,

[OPTIONAL] Follow these [steps](https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site#creating-your-site) to generate a Live Demo of your project and add the link to your Readme file

### That's it! :raised_hands: 

### Please :pray: make the changes :memo:  and submit back for a code review when you are done :rocket: 

Any questions? reach to me in slack ** @ Maru **

Happy Coding! :woman_technologist: 

PROJECT STATUS : REQUESTED CHANGES :vertical_traffic_light:

2020-02-08 15:28 UTC, euqueme commented on README.md
> +Link to live page
Please provide a link  to the Live Demo or remove this line (#9)

2020-02-08 15:28 UTC, euqueme commented on style.css
> +  width: 1440px;
Delete line #2 as the container should have 100% of the screen width

2020-02-10 18:44 UTC, pelzolga123 requested changes
Project requires changes.

2020-02-10 18:44 UTC, pelzolga123 commented
## Hi Maria! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!
Just one thing is left:
* [ ] All linter errors should be fixed. Project can't be approved until then. 
### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-02-10 19:46 UTC, addod19 approved these changes
## Status: Approved :+1:

Hi @Angelesh1995, **Congratulations on a job well done**. You have fix stickler errors as requested by the previous reviewer 😄 . You can now merge to master and submit project completion form.

Good luck with your next project 👍 
Happy coding 💻 
Daniel Larbi Addo

2020-02-10 20:58 UTC, merged